name: CI Pipeline

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build & Package
        run: |
          mkdir -p dist
          echo -e "Hey Rustam\nYou're a DevOps Ninja\nUnstoppable!!!" > dist/output.txt
          ls -l dist/

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/
          retention-days: 3
