name: CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  DEV:
    runs-on: ubuntu-latest
    environment:
      name: Dev

    steps:
      - name: Deploy
        run: echo "Deploying to Dev"

  STAGE:
    runs-on: ubuntu-latest
    environment:
      name: Stage
      url: https://stg.example-prod-url.com

    needs: DEV
    steps:
      - name: Deploy
        run: echo "Deploying to Stage"

  upload-success:
    runs-on: ubuntu-latest
    needs: [DEV, STAGE]
    steps:
      - name: Create success artifact
        run: echo "CI Pipeline Passed" > success.txt

      - name: Upload success artifact
        uses: actions/upload-artifact@v4
        with:
          name: success-artifact
          path: success.txt
