name: pipeline for next app

on:
  push:
    branches:
      - main

jobs:
  # Build job
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout the repostiory
  #       uses: actions/checkout@v4
  #     - name: Build the image
  #       uses: docker build -t node-app:latest .
  #     - name: List the built Docker image
  #       run: docker image ls

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install node
        uses: actions/setup-node@v4

      - name: install dependencies
        run: |
          cd todo
          npm ci

      - name: build project
        run: |
          cd todo
          npm build

      - name: upload artifact to enable deployment
        uses: actions/upload-artifact@v4
        with:
          name: production file
          path: ./todo/build

  # Deploy job
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: production file
          path: ./todo/build

      # - name: Deploy to ...
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.KEY }} #this is the key of the access token
      #     publish_dir: ./todo/build
