name: Deploy to Prod Pipeline

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist/

      - name: Verify Artifact Contents
        run: ls -l dist/

      - name: Show Artifact Contents
        run: cat dist/output.txt

      - name: Deploy to Production
        run: echo "Deploying using files from dist/"
