name: Deploy to Staging

on:
  workflow_run:
    workflows: ['CI Pipeline'] # Must match the workflow name in `ci.yml`
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' || 
      (github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: /dist/

      - name: Verify Artifact Contents
        run: ls -l /dist/

      - name: Show Artifact Contents
        run: cat /dist/output.txt

      - name: Deploy to Staging
        run: echo "Deploying using files from /dist/"
