name: Deploy to Staging Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist/

      - name: Verify Artifact Contents
        run: ls -l dist/

      - name: Show Artifact Contents
        run: cat dist/output.txt

      - name: Deploy to Staging
        run: echo "Deploying using files from dist/"
