name: Publish to PyPI
on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - run: echo 'Node app deployed! ✅'

      - name: Create GitHub Release
        # The GitHub CLI can't access the secrets context directly, so it's assigned to a local environment variable for access.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo 'Creating release...'
        # run: gh release create ${{ github.ref_name }} ./dist/* --generate-notes
