name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      run-e2e:
        description: 'Run E2E tests'
        required: true
        default: 'yes'
        type: choice
        options:
          - 'yes'
          - 'no'

jobs:
  # Core CI jobs (automated tests)
  lint:
    name: Lint
    runs-on: ubuntu-latest
    # Skip this job if it's a manual trigger specifically for E2E
    if: github.event_name != 'workflow_dispatch' || github.event.inputs.run-e2e != 'yes'
    steps:
      # - uses: actions/checkout@v4
      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '18'
      #     cache: 'npm'
      # - run: npm ci
      # - run: npm run lint
      - run: echo 'Running linting...'

  # audit:
  #   name: Audit
  #   runs-on: ubuntu-latest
  #   needs: lint
  #   # Skip this job if it's a manual trigger specifically for E2E
  #   if: github.event_name != 'workflow_dispatch' || github.event.inputs.run-e2e != 'yes'
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '18'
  #         cache: 'npm'
  #     - run: npm ci
  #     - run: npm audit --production

  # unit-tests:
  #   name: Unit Tests
  #   runs-on: ubuntu-latest
  #   needs: audit
  #   # Skip this job if it's a manual trigger specifically for E2E
  #   if: github.event_name != 'workflow_dispatch' || github.event.inputs.run-e2e != 'yes'
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '18'
  #         cache: 'npm'
  #     - run: npm ci
  #     - run: npm run test:unit
  #     # Save test status for other jobs to reference
  #     - name: Create status file
  #       if: always()
  #       run: echo ${{ job.status }} > unit-test-status.txt
  #     - name: Upload status
  #       if: always()
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: test-status
  #         path: unit-test-status.txt
  #         retention-days: 1

  # Optional E2E tests for manual trigger or feature branches
  e2e-tests-optional:
    name: E2E Tests (Optional)
    runs-on: ubuntu-latest
    needs: [lint]
    if: |
      (github.event_name == 'workflow_dispatch' && github.event.inputs.run-e2e == 'yes') ||
      (github.event_name == 'push' && github.ref != 'refs/heads/main')
    steps:
      # - uses: actions/checkout@v4
      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '18'
      #     cache: 'npm'
      # - run: npm ci
      # - run: npm run build
      # - run: npm run test:e2e
      - run: echo 'Running OPTIONAL e2e tests...'

  # Mandatory E2E tests for PR merges to main
  e2e-tests-mandatory:
    name: E2E Tests (Mandatory)
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    steps:
      # - uses: actions/checkout@v4
      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '18'
      #     cache: 'npm'
      # - run: npm ci
      # - run: npm run build
      # - run: npm run test:e2e
      - run: echo 'Running MERGING e2e tests...'
