name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Core CI jobs (lint/audit/unit)
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request_target'
    steps:
      # - uses: actions/checkout@v4
      # - run: npm ci
      # - run: npm run lint
      - run: echo 'Running linting...'

  audit:
    name: Audit
    runs-on: ubuntu-latest
    needs: lint
    if: github.event_name != 'pull_request_target'
    steps:
      # - uses: actions/checkout@v4
      # - run: npm ci
      # - run: npm audit
      - run: echo 'Running audit...'

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: audit
    if: github.event_name != 'pull_request_target'
    steps:
      # - uses: actions/checkout@v4
      # - run: npm ci
      # - run: npm run test:unit
      - run: echo 'Running unit tests...'

  e2e-optional:
    name: E2E Tests (Optional)
    runs-on: ubuntu-latest
    needs: [lint, audit, unit-tests]
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref_name != 'main')
    steps:
      # - uses: actions/checkout@v4
      # - run: npm ci
      # - run: npm run build
      # - run: npm run test:e2e
      - run: echo 'Running OPTIONAL e2e tests...'

  e2e-merge:
    name: E2E Tests (Mandatory on Merge)
    runs-on: ubuntu-latest
    needs: [lint, audit, unit-tests]
    if: github.event.pull_request.merged == true
    steps:
      # - uses: actions/checkout@v4
      # - run: npm ci
      # - run: npm run build
      # - run: npm run test:e2e
      - run: echo 'Running MERGING e2e tests...'
