name: Main Pipeline

on:
  pull_request:
    branches:
      - main # Change this to your main branch name

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Change this as needed

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build # Ensure tests only run after a successful build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: test # Deploy only if tests pass
    steps:
      - name: Deploying Application
        run: echo "Deploying application..."
